name: Lighthouse CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main # Runs on every pull request to main
  # schedule:
  # - cron: '0 0 * * 0' # Runs weekly

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Lighthouse CI
        run: npm install -g @lhci/cli

      - name: Run Lighthouse Tests
        run: |
          mkdir -p lhci_reports
          lhci collect --json > lhci_reports/lighthouse-results.json
          cat lhci_reports/lighthouse-results.json | jq '.[] | {url: .finalUrl, FCP: .audits["first-contentful-paint"].displayValue, LCP: .audits["largest-contentful-paint"].displayValue, CLS: .audits["cumulative-layout-shift"].displayValue, TTI: .audits["interactive"].displayValue}'

      - name: Upload Lighthouse Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: lhci_reports/
          retention-days: 30 # Keep reports for 30 days

